[build.environment]
    NPM_FLAGS = "--prefix=/dev/null"
    NODE_VERSION = "16.3.0"
    
[build]
  command = "pnpm run build || ( npm install pnpm && pnpm run build )"
  publish = "build/"
  functions = "functions/"